"""Read current geometry into reusable generation decisions; no output-shape template.
This is a measured rule planner, not a finished growth operator.
"""
import argparse,json
from pathlib import Path
import numpy as np
from compas.datastructures import Mesh

def analyze(data):
    mesh=Mesh.from_vertices_and_faces(data['vertices'],data['faces'])
    descriptors={};normals={f:np.array(mesh.face_normal(f)) for f in mesh.faces()}
    for f in mesh.faces():
        p=np.array(mesh.face_coordinates(f));center=p.mean(0)
        _,s,axes=np.linalg.svd(p-center,full_matrices=False)
        span=np.ptp((p-center)@axes.T,axis=0);long=max(span[0],1e-12);short=max(span[1],1e-12)
        bends=[float(np.arccos(np.clip(np.dot(normals[f],normals[k]),-1,1))) for k in mesh.face_neighbors(f)]
        descriptors[f]=dict(center=center.tolist(),normal=normals[f].tolist(),area=float(mesh.face_area(f)),long_span=float(long),short_span=float(short),aspect=float(long/short),max_dihedral=max(bends or [0]),flow_axis=axes[0].tolist(),neighbors=mesh.face_neighbors(f))
    areas=np.array([d['area'] for d in descriptors.values()]);threshold=float(np.quantile(areas,.55))
    candidates=[]
    for f,d in descriptors.items():
        transition=abs(d['normal'][2]);bend=d['max_dihedral']
        eligible=.12<transition<.98 and d['area']>=threshold*(1-1e-9) and d['aspect']<9 and bend>.15
        d['candidate']=bool(eligible)
        # Neighborhood footprint, not an externally placed pedestal primitive.
        patch=[f]+[k for k in d['neighbors'] if np.dot(normals[f],normals[k])>.88 and descriptors[k]['area']<3*d['area']]
        d['support_patch']=patch
        d['support_area']=sum(descriptors[k]['area'] for k in patch)
        d['score']=float(np.sqrt(d['support_area'])*transition*min(bend,1.5)) if eligible else 0.
        if eligible:candidates.append(f)
    return dict(faces=descriptors,candidates=sorted(candidates,key=lambda f:descriptors[f]['score'],reverse=True),rule='current adjacency + normal change + footprint size; no selected height bands or eight-sector indexing',limitations=['axis currently supplied as global Z for column study','candidate patches overlap; orbit grouping and nonoverlap scheduling are pending','PCA axes have sign ambiguity; orientation must be inherited from parent before growth','no geometry generated by this planner'])

if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('input',type=Path);p.add_argument('output',type=Path);a=p.parse_args()
    data=json.loads(a.input.read_text());result=analyze(data);a.output.parent.mkdir(exist_ok=True,parents=True);a.output.write_text(json.dumps(result,indent=2))
    # Scale-equivariance: same faces should be selected after uniform size change.
    scaled={**data,'vertices':(np.array(data['vertices'])*2.3).tolist()};check=analyze(scaled)
    assert set(result['candidates'])==set(check['candidates'])
    print(json.dumps(dict(faces=len(result['faces']),candidates=len(result['candidates']),scale_equivariance=True)))
